name: Book Reservation
on: [push]

jobs:
  book-reservation-1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Book reservation
      run: |
        python concierge.py --email ${{ secrets.USER_EMAIL }} --password ${{ secrets.USER_PASSWORD }} --api-key ${{ secrets.API_KEY }} --venue-id 1505 --party-size 2 --times 18:30:00 18:45:00 19:00:00 19:30:00 19:45:00 20:00:00 --date 2023-01-13 --time-to-book 14:00
  
  book-reservation-2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Book reservation
      run: |
        python concierge.py --email ${{ secrets.USER_EMAIL }} --password ${{ secrets.USER_PASSWORD }} --api-key ${{ secrets.API_KEY }} --venue-id 443 --party-size 2 --times 18:30:00 18:45:00 19:00:00 19:30:00 19:45:00 20:00:00 --date 2023-01-20 --time-to-book 05:00