name: Book Reservation 1
on:
  schedule:
  - cron: "00 13 * * *"

jobs:
  book-reservation-1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Book reservation
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 360
        max_attempts: 4
        retry_on: timeout
        command: |
          python concierge.py --email ${{ secrets.USER_EMAIL }} --password ${{ secrets.USER_PASSWORD }} --api-key ${{ secrets.API_KEY }} --venue-id 1505 --party-size 2 --times 19:30:00 19:00:00 19:45:00 20:00:00 20:30:00 --date 2023-02-14 --time-to-book 14:00
  book-reservation-2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Book reservation
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 360
        max_attempts: 4
        retry_on: timeout
        command: |
          python concierge.py --email ${{ secrets.USER_EMAIL }} --password ${{ secrets.USER_PASSWORD }} --api-key ${{ secrets.API_KEY }} --venue-id 1505 --party-size 2 --times 19:00:00 19:15:00 19:30:00 19:45:00 20:00:00 20:15:00 20:30:00 20:45:00 21:00:00 21:15:00 --date 2023-02-11 --time-to-book 14:00
